'use client'

import {useState} from 'react'

type AgentBrief = {
  mode: string
  usageRequestId: string
  statusReceipt: {
    current: 'CLEAR' | 'BLOCK' | 'REVIEW' | 'UNKNOWN'
    proposed: 'CLEAR' | 'BLOCK' | 'REVIEW' | 'UNKNOWN'
    authority: string
  }
  summary: string
  findings: Array<{
    axis: string
    status: string
    reason: string
    causedBy: string[]
  }>
  evidence: Array<{
    requestedDocumentId: string
    kbStatus: string
    sourceStatus: string
    sourceClause: string | null
    source: string | null
  }>
  repairOptions: Array<{
    id: string
    label: string
    description: string
  }>
  abstention: {
    active: boolean
    reason: string | null
  }
  nextAction: string
  toolTrace: Array<{
    tool: string
    purpose: string
    authority: string
    result: string
  }>
  writeAuthority: 'NONE'
  aiNarrative: {
    status: 'generated' | 'not_configured' | 'rejected' | 'unavailable'
    text: string | null
    provider: 'sanity-content-agent'
  }
  observedAt: string
}

function Status({value}: {value: string}) {
  return <span className={`status status--${value.toLowerCase()}`}>{value}</span>
}

export default function ClearanceAgentPanel({
  usageRequestId,
  proposedPerspective,
}: {
  usageRequestId: string
  proposedPerspective: string
}) {
  const [brief, setBrief] = useState<AgentBrief | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function investigate() {
    setBusy(true)
    setError(null)

    try {
      const response = await fetch('/api/agent', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({usageRequestId, proposedPerspective}),
      })
      const payload = await response.json()
      if (!response.ok) throw new Error(payload.error || 'Agent investigation failed')
      setBrief(payload)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Agent investigation failed')
    } finally {
      setBusy(false)
    }
  }

  return (
    <article className="agentLayer" aria-label={brief ? 'Agent explanation' : 'Agent boundary'}>
      <div className="agentLayerHead">
        <span className="agentLayerLabel">{brief ? 'Sanity Content Agent · run result' : 'Sanity Content Agent · on demand'}</span>
        <span className="authorityBadges">
          <span className="authorityBadge">Decision authority · none</span>
          <span className="authorityBadge">Write authority · {brief?.writeAuthority ?? 'NONE'}</span>
        </span>
      </div>

      <p className="agentLayerIntro">
        The agent explains the verdict above. It cannot create a clearance status and cannot execute a mutation.
        It runs only when you ask, and may consume Sanity AI credits.
      </p>

      {!brief && (
        <button className="secondaryButton" onClick={investigate} disabled={busy}>
          {busy ? 'Investigating…' : 'Ask the agent to explain'}
        </button>
      )}

      {error && (
        <div className="errorBanner">
          Agent dependency failure: {error}. No clearance status was generated by the agent.
        </div>
      )}

      {brief && (
        <div className="agentResult">
          <p className="agentReceiptLine">
            Checked against the deterministic receipt:{' '}
            <Status value={brief.statusReceipt.current} /> <span aria-hidden="true">→</span> <Status value={brief.statusReceipt.proposed} />
          </p>

          {brief.aiNarrative.status === 'generated' && brief.aiNarrative.text ? (
            <blockquote className="agentNarrativeText">{brief.aiNarrative.text}</blockquote>
          ) : brief.aiNarrative.status === 'rejected' ? (
            <div className="errorBanner">
              AI narrative was rejected because it contradicted the deterministic status receipt.
            </div>
          ) : brief.aiNarrative.status === 'unavailable' ? (
            <p className="agentQuiet">AI explanation is temporarily unavailable. The deterministic receipt and tool evidence remain authoritative.</p>
          ) : (
            <p className="agentQuiet">Sanity Content Agent is not configured for this runtime. The bounded tool summary below remains available without AI narration.</p>
          )}

          <p className="agentSummary">{brief.summary}</p>

          {brief.abstention.active && (
            <p className="agentAbstention"><strong>Agent abstention.</strong> {brief.abstention.reason}</p>
          )}

          <p className="agentNext"><strong>Bounded next action.</strong> {brief.nextAction}</p>

          <details className="caseDisclosure">
            <summary>Tool trace and evidence gathered ({brief.toolTrace.length} tools)</summary>
            <div className="agentToolGrid">
              {brief.toolTrace.map((tool) => (
                <div className="agentTool" key={tool.tool}>
                  <strong>{tool.tool}</strong>
                  <span>{tool.purpose}</span>
                  <small>{tool.authority}</small>
                  <em>{tool.result}</em>
                </div>
              ))}
            </div>
            <div className="agentEvidence">
              {brief.evidence.length === 0 ? (
                <span>No causal evidence record was available for this state.</span>
              ) : (
                brief.evidence.map((item) => (
                  <div key={item.requestedDocumentId}>
                    <code>{item.requestedDocumentId}</code>
                    <span>KB: {item.kbStatus} · structured source: {item.sourceStatus}</span>
                  </div>
                ))
              )}
            </div>
            {brief.repairOptions.length > 0 && (
              <p className="agentQuiet">Registry-backed proposals only: {brief.repairOptions.map((repair) => repair.label).join(' · ')}. Execution stays in the human-approved control.</p>
            )}
          </details>

          <button className="textButton" onClick={investigate} disabled={busy}>
            {busy ? 'Refreshing…' : 'Re-run explanation'}
          </button>
        </div>
      )}
    </article>
  )
}
