'use client'

import {useState} from 'react'

type AgentBrief = {
  mode: string
  usageRequestId: string
  statusReceipt: {
    current: 'CLEAR' | 'BLOCK' | 'REVIEW' | 'UNKNOWN'
    proposed: 'CLEAR' | 'BLOCK' | 'REVIEW' | 'UNKNOWN'
    authority: string
  }
  summary: string
  findings: Array<{
    axis: string
    status: string
    reason: string
    causedBy: string[]
  }>
  evidence: Array<{
    requestedDocumentId: string
    kbStatus: string
    sourceStatus: string
    sourceClause: string | null
    source: string | null
  }>
  repairOptions: Array<{
    id: string
    label: string
    description: string
  }>
  abstention: {
    active: boolean
    reason: string | null
  }
  nextAction: string
  toolTrace: Array<{
    tool: string
    purpose: string
    authority: string
    result: string
  }>
  writeAuthority: 'NONE'
  observedAt: string
}

function Status({value}: {value: string}) {
  return <span className={`status status--${value.toLowerCase()}`}>{value}</span>
}

export default function ClearanceAgentPanel({
  usageRequestId,
  proposedPerspective,
}: {
  usageRequestId: string
  proposedPerspective: string
}) {
  const [brief, setBrief] = useState<AgentBrief | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function investigate() {
    setBusy(true)
    setError(null)

    try {
      const response = await fetch('/api/agent', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({usageRequestId, proposedPerspective}),
      })
      const payload = await response.json()
      if (!response.ok) throw new Error(payload.error || 'Agent investigation failed')
      setBrief(payload)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Agent investigation failed')
    } finally {
      setBusy(false)
    }
  }

  return (
    <article className="panel agentPanel">
      <div className="panelHeading">
        <span className="stepIndex">AI</span>
        <div>
          <p className="cardKicker">Bounded clearance agent</p>
          <h3>Investigate with Context MCP + deterministic receipts</h3>
        </div>
        <span className="authorityBadge">WRITE AUTHORITY · NONE</span>
      </div>

      <p className="muted">
        The agent may gather, explain, and propose. It cannot create a clearance status and it cannot execute a mutation.
      </p>

      {!brief && (
        <button className="secondaryButton" onClick={investigate} disabled={busy}>
          {busy ? 'Investigating…' : 'Run bounded investigation'}
        </button>
      )}

      {error && (
        <div className="errorBanner">
          Agent dependency failure: {error}. No clearance status was generated by the agent.
        </div>
      )}

      {brief && (
        <div className="agentResult">
          <div className="transition">
            <Status value={brief.statusReceipt.current} />
            <span className="arrow">→</span>
            <Status value={brief.statusReceipt.proposed} />
            <span className="authorityBadge">DETERMINISTIC RECEIPT</span>
          </div>

          <p>{brief.summary}</p>

          {brief.abstention.active && (
            <div className="proposalNote">
              <strong>Agent abstention</strong>
              <span>{brief.abstention.reason}</span>
            </div>
          )}

          <div className="agentToolGrid">
            {brief.toolTrace.map((tool) => (
              <div className="agentTool" key={tool.tool}>
                <strong>{tool.tool}</strong>
                <span>{tool.purpose}</span>
                <small>{tool.authority}</small>
                <em>{tool.result}</em>
              </div>
            ))}
          </div>

          <div className="agentEvidence">
            <strong>Evidence gathered</strong>
            {brief.evidence.length === 0 ? (
              <span>No causal evidence record was available for this state.</span>
            ) : (
              brief.evidence.map((item) => (
                <div key={item.requestedDocumentId}>
                  <code>{item.requestedDocumentId}</code>
                  <span>KB: {item.kbStatus} · structured source: {item.sourceStatus}</span>
                  {item.sourceClause && <blockquote>{item.sourceClause}</blockquote>}
                </div>
              ))
            )}
          </div>

          <div className="agentNextAction">
            <strong>Bounded next action</strong>
            <span>{brief.nextAction}</span>
          </div>

          {brief.repairOptions.length > 0 && (
            <div className="agentRepairs">
              <strong>Registry-backed proposals only</strong>
              {brief.repairOptions.map((repair) => (
                <div key={repair.id}>
                  <span>{repair.label}</span>
                  <small>{repair.description}</small>
                </div>
              ))}
              <small>Execution remains in the separate human-approved remediation control.</small>
            </div>
          )}

          <button className="textButton" onClick={investigate} disabled={busy}>
            {busy ? 'Refreshing…' : 'Re-run investigation'}
          </button>
        </div>
      )}
    </article>
  )
}
